title: Michael S
description:
  With over a decade of experience as a Data Scientist at UTS Business School, I leverage my PhD in Statistics and my expertise in machine learning and data mining to develop data-driven solutions that inform business decisions and strategies. 
<br><br>
  Technical Skills:
<br><br>
  - Programming: Python, SQL, R, STATA, SAS
  - Data Visualization: Tableau, Power BI
<br><br>
theme: jekyll-theme-minimal


