title: **Michael S**

description: > 
  <div style="line-height: 1.6;">
    With over a decade of experience as a Data Scientist at UTS Business School, I leverage my PhD in Statistics and my skills in machine learning and data mining to create data-driven solutions that inform business decisions and strategies.
    <br><br>
    <h2>Technical Skills</h2>
    <br><br>
    <strong>Programming:</strong> Python, SQL, R, STATA, SAS
    <br><br>
    <strong>Data Visualization:</strong> Tableau, Power BI
  </div>

theme: jekyll-theme-minimal
