title: "Michael S"

description: >
  With over a decade of experience as a Data Scientist at UTS Business School, I leverage my PhD in Statistics and my skills in machine learning and data mining to create data-driven solutions that inform business decisions and strategies.
  <br><br>
  <h2>Technical Skills</h2>
  <h3>Programming:</h3> Python, SQL, R, STATA, SAS
  <br><br>
  <h3>Data Visualization:</h3> Tableau, Power BI
  <br><br>
  <h4>Qualifications<h4>
  <h5>PhD in Economics (Statistics)      
  CPA Program
  Master of Professional Accounting
  Bachelor of Economics (Finance)</h5>


theme: jekyll-theme-minimal
