title: Michael S

description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>
  With over a decade of experience as a Data Scientist at UTS Business School, I leverage my PhD in Statistics and my skills in machine learning and data mining to create data-driven solutions that inform business decisions and strategies. 
  <br><br>
  
  <br><br>
  
theme: jekyll-theme-minimal

